### ISSUE TITLE
Search function followup

### ISSUE THREAD

**Issue by imswebra** [CMPUT301F20T01/Bookmark#72]
### Rationale
Follow-up to 03.01.01 (#11) and 03.02.01 (#17), the search functionality should be updated to function as originally discussed during design phase (expanding nav bar, filtering in line). This ticket will also likely compliment #71, as both will likely be implemented using listadapter filters.

#### Story Points
5

#### Risk Level
low

**Comment by ryankortbeek** [comment]
@imswebra this is done [here](https://github.com/CMPUT301F20T01/Bookmark/pull/104)
